export const ROUTES = {
  HOME: "(tabs)",
  MY_PROFILE: "screens/(account)/MyProfile",
  NOTIFICATIONS: "screens/(account)/Notifications",
  SETTINGS: "screens/(account)/SettingsScreen",
  PAYMENT_METHODS: "screens/(account)/PaymentMethods",
  ADD_PAYMENT_METHOD: "screens/(account)/AddNewPaymentCard",
  ACCOUNT_TAB: "(tabs)/account",
  NEW_PASSWORD: "screens/(account)/NewPassword",
  NEW_EMAIL: "screens/(account)/NewEmail",
  NEW_PHONE: "screens/(account)/NewMobile",
  OTP_SCREEN: "screens/(account)/OTPVerification",
  LOGIN: "screens/(auth)/Login",
  REGISTER: "screens/(auth)/Signup",
  OTP: "screens/(auth)/OTP",
  THEME_TOGGLE: "screens/(account)/ThemeToggle",
};
