export const ROUTES = {
  HOME: "(tabs)",
  MY_PROFILE: "screens/(account)/MyProfile",
  NOTIFICATIONS: "screens/(account)/Notifications",
  SETTINGS: "screens/(account)/SettingsScreen",
  PAYMENT_METHODS: "screens/(account)/PaymentMethods",
  ADD_PAYMENT_METHOD: "screens/(account)/AddNewPaymentCard",
  ACCOUNT_TAB: "(tabs)/account",
  NEW_PASSWORD: "screens/(account)/NewPassword",
  NEW_EMAIL: "screens/(account)/NewEmail",
  NEW_PHONE: "screens/(account)/NewMobile",
  OTP_SCREEN: "screens/(account)/OTPVerification",
  LOGIN: "screens/(auth)/Login",
  REGISTER: "screens/(auth)/Signup",
  FORGOT_PASS_OPTION: "screens/(auth)/ForgotPasswordOption",
  FORGOT_BY_EMAIL: "screens/(auth)/ForgotByEmail",
  FORGOT_BY_PHONE: "screens/(auth)/ForgotByPhone",
  RESET_PASS: "screens/(auth)/ResetPassword",
  OTP: "screens/(auth)/OTP",
  THEME_TOGGLE: "screens/(account)/ThemeToggle",
  BOOK_SERVICE: "screens/(home)/booking/BookService",
  MY_BOOKINGS: "screens/(home)/booking/MyBookings/Bookings",
  BOOKED_SERVIICE_DETAIL:
    "screens/(home)/booking/MyBookings/BookedServiceDetail",
  SERVICE_LISTING: "screens/(home)/ServiceListing",
};
